{
	"source":{
		"url":"http://activedata.allizom.org/query"
	},
	"destination": {
		"host": "http://activedata.allizom.org",
		"port": 9200,
		"index": "unittest-summary",
		"type": "test_summary",
		"timeout": 300,
		"schema": {
			"$ref": "//../schema/test_summary.json"
		},
		"debug": false,
		"limit_replicas": false
	},
	"constants": {
		"pyLibrary.env.http.default_headers": {
			"referer": "https://github.com/klahnakoski/TestFailures"
		}
	},
	"debug": {
		"trace": true,
		"cprofile": {
			"enabled": false,
			"filename": "./results/profile.tab"
		},
		"log": [
			{
				"log_type": "console"
			},
			{
				"class": "logging.handlers.RotatingFileHandler",
				"filename": "logs/test_summary_agg.log",
				"maxBytes": 10000000,
				"backupCount": 10,
				"encoding": "utf8"
			},
			{
				"log_type": "ses",
				"$ref": "file://~/private.json#aws_credentials",
				"from_address": "klahnakoski@mozilla.com",
				"to_address": "klahnakoski@mozilla.com",
				"subject": "[ALERT][Staging] Problem in Test Failure Summary"
			}
		]
	}
}
